import type { ReactNode } from 'react';
import { clients } from '@/content/clients';
import {
  Container,
  Eyebrow,
  Heading,
  Prose,
  Section,
  cx,
} from '@/components/ui';
import type { HeadingLevel, SectionDensity, Surface } from '@/components/ui';
import type { LogoItem } from './types';

/**
 * The only counts that divide the sets with zero dead cells: 7 for the 21
 * clients, 5 for the 10 sponsors. Each steps down to its own smaller divisor
 * (3 and 2) rather than to a count that leaves a ragged tail at exactly the
 * width a meeting planner on a laptop sees.
 */
export type LogoWallColumns = 7 | 5;

const COLUMN_CLASS: Record<LogoWallColumns, string> = {
  7: 'dm-logowall--cols-7',
  5: 'dm-logowall--cols-5',
};

/** Anything past this ratio is width-constrained and backs off to 0.86 so it
 *  does not outweigh the square marks beside it. usaedc is 3.55:1. */
const WIDE_RATIO = 3;

/** Every logo has a .webp sibling at identical dimensions, generated by
 *  scripts/normalize-assets.mjs. Nothing here invents a file that is not on
 *  disk: the one source that was already .webp gets no extra <source>. */
function webpSibling(logo: string): string | null {
  const dot = logo.lastIndexOf('.');
  if (dot === -1) return null;
  const ext = logo.slice(dot + 1).toLowerCase();
  if (ext === 'webp' || ext === 'svg') return null;
  return `${logo.slice(0, dot)}.webp`;
}

type LogoCellProps = {
  item: LogoItem;
  /** "01" through "21". Decoration, and hidden from assistive tech. */
  index?: string;
  linked: boolean;
};

function LogoCell({ item, index, linked }: LogoCellProps) {
  const wide = item.height > 0 && item.width / item.height >= WIDE_RATIO;
  const webp = webpSibling(item.logo);

  const mark = (
    <picture>
      {webp ? <source srcSet={webp} type="image/webp" /> : null}
      {/* A raw <img> rather than next/image on purpose: these 31 marks are
          already normalized to their final dimensions, they carry
          mix-blend-mode and a filter that have to land on the element itself,
          and none of them is ever the LCP. */}
      <img
        className="dm-logo-cell__img"
        src={item.logo}
        alt={item.name}
        width={item.width}
        height={item.height}
        loading="lazy"
        decoding="async"
      />
    </picture>
  );

  return (
    <li className={cx('dm-logo-cell', wide && 'dm-logo-cell--wide')}>
      {index ? (
        <span className="dm-logo-cell__index" aria-hidden="true">
          {index}
        </span>
      ) : null}
      {linked && item.url ? (
        <a
          className="dm-logo-cell__link dm-link-bare"
          href={item.url}
          target="_blank"
          rel="noopener noreferrer"
        >
          {mark}
          <span className="sr-only">, opens in a new tab</span>
        </a>
      ) : (
        mark
      )}
    </li>
  );
}

export type LogoWallProps = {
  /** Defaults to the 21 normalized client marks. */
  items?: LogoItem[];
  /** 7 for a set of 21, 5 for a set of 10. */
  columns?: LogoWallColumns;
  /**
   * Client marks are not links, because the client set has no URLs and a dead
   * link is worse than no link. The sponsor wall passes true and every item
   * that carries a URL becomes a cell-sized target.
   */
  linked?: boolean;
  /** Corner indices, --ink-faint and aria-hidden. Off by default. */
  indices?: boolean;
  id?: string;
  eyebrow?: ReactNode;
  title?: ReactNode;
  /** Rank, independent of size. Defaults to h2. */
  level?: HeadingLevel;
  /** The numbered prefix, e.g. "No. 04", rendered inside the heading. */
  folio?: string;
  /**
   * The mono section metadata line, one of the three standing slots the dry
   * humor lives in. Defaults to "21 of 2,400+". Pass null to drop it.
   */
  meta?: ReactNode;
  /** Optional prose between the head and the grid. */
  intro?: ReactNode;
  surface?: Surface;
  density?: SectionDensity;
  className?: string;
};

/**
 * The client wall. 21 marks of wildly mixed quality, aspect ratio and
 * background, every one of them shipping an opaque white or near-white field.
 *
 * The normalization that keeps a 148 by 148 square and a 423 by 119 banner at
 * the same optical weight lives in src/styles/sections-core.css: a height cap
 * AND a width cap, contrast-lifted grayscale, multiply on bone and invert plus
 * screen on navy, and optical centering.
 *
 * Column counts are locked by docs/DESIGN_SYSTEM.md section 7.2 and are not a
 * matter of taste: 7 at 1024 and up, 3 below it, because 7 and 3 are the only
 * counts that divide 21 with no dead cells.
 */
export function LogoWall({
  items,
  columns = 7,
  linked = false,
  indices = false,
  id,
  eyebrow,
  title,
  level = 2,
  folio,
  meta,
  intro,
  surface,
  density,
  className,
}: LogoWallProps) {
  const marks = items ?? clients;
  const headingId = id ? `${id}-title` : undefined;
  const metaLine = meta !== undefined ? meta : `${marks.length} of 2,400+`;

  return (
    <Section
      id={id}
      aria-labelledby={headingId}
      surface={surface}
      density={density}
      className={cx('dm-logowall', COLUMN_CLASS[columns], className)}
    >
      <Container width="wide">
        {eyebrow || title || metaLine ? (
          <div className="dm-logowall__head">
            <div>
              {eyebrow ? <Eyebrow>{eyebrow}</Eyebrow> : null}
              {title ? (
                <Heading
                  level={level}
                  size="2xl"
                  folio={folio}
                  id={headingId}
                  className="dm-logowall__title"
                >
                  {title}
                </Heading>
              ) : null}
            </div>
            {metaLine ? <Eyebrow className="dm-logowall__meta">{metaLine}</Eyebrow> : null}
          </div>
        ) : null}

        {intro ? (
          <Prose className="dm-logowall__intro">
            {typeof intro === 'string' ? <p>{intro}</p> : intro}
          </Prose>
        ) : null}

        <ul className="dm-logowall__grid" role="list">
          {marks.map((item, i) => (
            <LogoCell
              key={item.logo}
              item={item}
              index={indices ? String(i + 1).padStart(2, '0') : undefined}
              linked={linked}
            />
          ))}
        </ul>
      </Container>
    </Section>
  );
}

export default LogoWall;
