import type { ReactNode } from 'react';
import { clients } from '@/content/clients';
import {
  Container,
  Eyebrow,
  Heading,
  Prose,
  Section,
  cx,
} from '@/components/ui';
import type { HeadingLevel, SectionDensity, Surface } from '@/components/ui';
import type { LogoItem } from './types';

/**
 * The only counts that divide the sets with zero dead cells: 7 for the 21
 * clients, 5 for the 10 sponsors. Each steps down to its own smaller divisor
 * (3 and 2) rather than to a count that leaves a ragged tail at exactly the
 * width a meeting planner on a laptop sees.
 */
export type LogoWallColumns = 7 | 5;

const COLUMN_CLASS: Record<LogoWallColumns, string> = {
  7: 'dm-logowall--cols-7',
  5: 'dm-logowall--cols-5',
};

/** Every logo has a .webp sibling at identical dimensions, generated by
 *  scripts/normalize-assets.mjs. Nothing here invents a file that is not on
 *  disk: the one source that was already .webp gets no extra <source>. */
function webpSibling(logo: string): string | null {
  const dot = logo.lastIndexOf('.');
  if (dot === -1) return null;
  const ext = logo.slice(dot + 1).toLowerCase();
  if (ext === 'webp' || ext === 'svg') return null;
  return `${logo.slice(0, dot)}.webp`;
}

/**
 * The file stem, which is the key src/styles/logo-optical.css writes its
 * per-mark optical factor against. Derived rather than stored so a logo can
 * never carry a slug that points at a file that is not on disk: the wall reads
 * the same string the <img src> does.
 */
function logoSlug(logo: string): string {
  const file = logo.slice(logo.lastIndexOf('/') + 1);
  const dot = file.lastIndexOf('.');
  return dot === -1 ? file : file.slice(0, dot);
}

type LogoCellProps = {
  item: LogoItem;
  /** "01" through "21". Decoration, and hidden from assistive tech. */
  index?: string;
  linked: boolean;
};

function LogoCell({ item, index, linked }: LogoCellProps) {
  const webp = webpSibling(item.logo);

  const mark = (
    <picture>
      {webp ? <source srcSet={webp} type="image/webp" /> : null}
      {/* A raw <img> rather than next/image on purpose: these 31 marks are
          already normalized to their final dimensions, they carry
          mix-blend-mode and a filter that have to land on the element itself,
          and none of them is ever the LCP. */}
      <img
        className="dm-logo-cell__img"
        /* The wall sizes this mark by optical area, and the factor that does
           it lives in src/styles/logo-optical.css keyed on this attribute.
           It is generated from the file's real dimensions by
           scripts/normalize-logo-ink.mjs, which is why the sizing is not an
           inline style: a number in the markup could drift from the file it
           describes, a generated stylesheet cannot. */
        data-logo={logoSlug(item.logo)}
        src={item.logo}
        alt={item.name}
        width={item.width}
        height={item.height}
        loading="lazy"
        decoding="async"
      />
    </picture>
  );

  return (
    <li className="dm-logo-cell">
      {index ? (
        <span className="dm-logo-cell__index" aria-hidden="true">
          {index}
        </span>
      ) : null}
      {linked && item.url ? (
        <a
          className="dm-logo-cell__link dm-link-bare"
          href={item.url}
          target="_blank"
          rel="noopener noreferrer"
        >
          {mark}
          <span className="sr-only">, opens in a new tab</span>
        </a>
      ) : (
        mark
      )}
    </li>
  );
}

export type LogoWallProps = {
  /** Defaults to the 21 normalized client marks. */
  items?: LogoItem[];
  /** 7 for a set of 21, 5 for a set of 10. */
  columns?: LogoWallColumns;
  /**
   * Client marks are not links, because the client set has no URLs and a dead
   * link is worse than no link. The sponsor wall passes true and every item
   * that carries a URL becomes a cell-sized target.
   */
  linked?: boolean;
  /** Corner indices, --ink-faint and aria-hidden. Off by default. */
  indices?: boolean;
  id?: string;
  eyebrow?: ReactNode;
  title?: ReactNode;
  /** Rank, independent of size. Defaults to h2. */
  level?: HeadingLevel;
  /** The numbered prefix, e.g. "No. 04", rendered inside the heading. */
  folio?: string;
  /**
   * The mono section metadata line, one of the three standing slots the dry
   * humor lives in. Defaults to "21 of 2,400+". Pass null to drop it.
   */
  meta?: ReactNode;
  /** Optional prose between the head and the grid. */
  intro?: ReactNode;
  surface?: Surface;
  density?: SectionDensity;
  className?: string;
};

/**
 * The client wall. 21 marks of wildly mixed quality, aspect ratio and
 * background, every one of them shipping an opaque white or near-white field.
 *
 * The normalization runs in two places and needs both. scripts/normalize-logo-
 * ink.mjs trims each file to its own ink, so the aspect ratio the cell sees is
 * the mark's and not the supplier's margin. src/styles/sections-core.css then
 * does the sizing: a height cap AND a width cap, contrast-lifted grayscale,
 * multiply on bone and invert plus screen on navy, and optical centering.
 *
 * Column counts are locked by docs/DESIGN_SYSTEM.md section 7.2 and are not a
 * matter of taste: 7 at 1024 and up, 3 below it, because 7 and 3 are the only
 * counts that divide 21 with no dead cells.
 */
export function LogoWall({
  items,
  columns = 7,
  linked = false,
  indices = false,
  id,
  eyebrow,
  title,
  level = 2,
  folio,
  meta,
  intro,
  surface,
  density,
  className,
}: LogoWallProps) {
  const marks = items ?? clients;
  const headingId = id ? `${id}-title` : undefined;
  const metaLine = meta !== undefined ? meta : `${marks.length} of 2,400+`;

  return (
    <Section
      id={id}
      aria-labelledby={headingId}
      surface={surface}
      density={density}
      className={cx('dm-logowall', COLUMN_CLASS[columns], className)}
    >
      {/* Two containers on purpose. The seven-column grid genuinely needs the
          wide measure, but the section HEAD does not, and when the head rode
          along with it every eyebrow, folio and H2 on a logo-wall section sat
          at x=48 while every other section on the same page sat at x=96. On
          Home that jog was directly visible between "For meeting planners" and
          "Client roster". The head now uses the standard container, so the
          site has one heading axis and the wall keeps its width. */}
      {eyebrow || title || metaLine || intro ? (
        <Container className="dm-logowall__lede">
          {eyebrow || title || metaLine ? (
            <div className="dm-logowall__head">
              <div>
                {eyebrow ? <Eyebrow>{eyebrow}</Eyebrow> : null}
                {title ? (
                  <Heading
                    level={level}
                    size="2xl"
                    folio={folio}
                    id={headingId}
                    className="dm-logowall__title"
                  >
                    {title}
                  </Heading>
                ) : null}
              </div>
              {metaLine ? <Eyebrow className="dm-logowall__meta">{metaLine}</Eyebrow> : null}
            </div>
          ) : null}

          {intro ? (
            <Prose className="dm-logowall__intro">
              {typeof intro === 'string' ? <p>{intro}</p> : intro}
            </Prose>
          ) : null}
        </Container>
      ) : null}

      <Container width="wide">
        {/* One observed container, not 21 observed cells. The stagger caps at
            five beats so the wall lands as a sweep rather than a queue. */}
        <ul className="dm-logowall__grid" role="list" data-reveal="stagger">
          {marks.map((item, i) => (
            <LogoCell
              key={item.logo}
              item={item}
              index={indices ? String(i + 1).padStart(2, '0') : undefined}
              linked={linked}
            />
          ))}
        </ul>
      </Container>
    </Section>
  );
}

export default LogoWall;
