/**
 * Damian's own marks. Paths only, so a component can reference a logo
 * without knowing which folder or file extension it landed in.
 *
 * Generated by scripts/normalize-assets.mjs. Every entry has a .webp
 * sibling at identical pixel dimensions in public/img/brand.
 *
 * One supplied mark is deliberately absent from this file and from public/
 * entirely. The client asked for it to be dropped, so it is neither
 * processed nor referenced anywhere. See the skipped list in
 * _source/asset-map.json.
 */

export const brandAssets = {
  wordmark: '/img/brand/wordmark.png', // site header and footer on every route, plus the OG card and the Organization logo in lib/schema.ts
  wordmarkWhite: '/img/brand/wordmark-white.png', // not placed anywhere: the wordmark never reverses. See DESIGN_SYSTEM section 10 rule 4
  boasg: '/img/brand/boasg.jpg', // /boasg/ share card
  boasgWhite: '/img/brand/boasg-white.png', // /boasg/ badge
  businessOfAgriculture: '/img/brand/business-of-agriculture.png', // /the-business-of-agriculture/, the stacked lockup leading the subscribe band
  businessOfAgriculturePodcast: '/img/brand/business-of-agriculture-podcast.jpg', // /the-business-of-agriculture/ and /podcasts/ cover art, and the PodcastSeries image
  granary: '/img/brand/the-granary.png', // /the-business-of-agriculture/ and /xtreme-ag/, the Granary show mark
  xtremeAg: '/img/brand/xtreme-ag.jpg', // /the-business-of-agriculture/, the XtremeAg partnership credit
} as const;

/**
 * Secondary marks that ship alongside the primary set. They are kept out of
 * brandAssets so that object stays a short, stable contract, but the files
 * are real and available if a page needs them.
 */

export const brandAssetsExtra = {
  boasgWhiteFlat: '/img/brand/boasg-white-flat.jpg', // unplaced, the opaque duplicate of the boasgWhite badge. See docs/CONTENT_MANIFEST.md
  doBusinessBetterPodcast: '/img/brand/do-business-better-podcast.png', // /podcasts/ and /do-business-better-podcast/ cover art, and the PodcastSeries image
  businessOfAgricultureLockup: '/img/brand/business-of-agriculture-lockup.png', // unplaced, the horizontal alternate to businessOfAgriculture
  businessOfAgricultureIconWhite: '/img/brand/business-of-agriculture-icon-white.png', // unplaced, the leaf icon on its own at favicon scale
  businessOfAgricultureAvatar: '/img/brand/business-of-agriculture-avatar.png', // unplaced, the square avatar the player embeds carry themselves
  xtremeAgTransparent: '/img/brand/xtreme-ag-transparent.png', // /podcasts/ and /xtreme-ag/, the transparent XtremeAg mark for placing on color
  dmMonogram: '/img/brand/dm-monogram.jpg', // never referenced by a route: this is the SOURCE the site icons were cut from, not a shipped image. See app/icon.png
} as const;

export type BrandAssetKey = keyof typeof brandAssets;
