/**
 * Damian's own marks. Paths only, so a component can reference a logo
 * without knowing which folder or file extension it landed in.
 *
 * Generated by scripts/normalize-assets.mjs. Every entry has a .webp
 * sibling at identical pixel dimensions in public/img/brand.
 *
 * One supplied mark is deliberately absent from this file and from public/
 * entirely. The client asked for it to be dropped, so it is neither
 * processed nor referenced anywhere. See the skipped list in
 * _source/asset-map.json.
 */

export const brandAssets = {
  wordmark: '/img/brand/wordmark.png', // site header and footer, all pages
  wordmarkWhite: '/img/brand/wordmark-white.png', // header over dark hero imagery, footer on the dark band
  boasg: '/img/brand/boasg.jpg', // /boasg/ hero and the join CTA, plus social share cards
  boasgWhite: '/img/brand/boasg-white.png', // /boasg/ badge placed over photography or a dark section
  businessOfAgriculture: '/img/brand/business-of-agriculture.png', // /podcast/ masthead and the home page podcast block
  businessOfAgriculturePodcast: '/img/brand/business-of-agriculture-podcast.jpg', // /podcast/ episode artwork and the feed cover
  granary: '/img/brand/the-granary.png', // /the-granary/ hero
  xtremeAg: '/img/brand/xtreme-ag.jpg', // /the-granary/ and /podcast/, the XtremeAg partnership credit
} as const;

/**
 * Secondary marks that ship alongside the primary set. They are kept out of
 * brandAssets so that object stays a short, stable contract, but the files
 * are real and available if a page needs them.
 */

export const brandAssetsExtra = {
  boasgWhiteFlat: '/img/brand/boasg-white-flat.jpg', // /boasg/, opaque white background variant for print or email
  doBusinessBetterPodcast: '/img/brand/do-business-better-podcast.png', // /about/#books and any Do Business Better cross promo
  businessOfAgricultureLockup: '/img/brand/business-of-agriculture-lockup.png', // /podcast/ alternate lockup on a dark panel
  businessOfAgricultureIconWhite: '/img/brand/business-of-agriculture-icon-white.png', // /podcast/ leaf icon over dark sections, favicon-scale use
  businessOfAgricultureAvatar: '/img/brand/business-of-agriculture-avatar.png', // /podcast/ square avatar for feed and player embeds
  xtremeAgTransparent: '/img/brand/xtreme-ag-transparent.png', // /the-granary/, transparent version for placing on color
  dmMonogram: '/img/brand/dm-monogram.jpg', // favicon and app icon source, site wide
} as const;

export type BrandAssetKey = keyof typeof brandAssets;
