/**
 * Client logos for the credibility strip.
 *
 * Generated by scripts/normalize-assets.mjs from the supplied "Client Logos"
 * folder. Do not hand edit the width and height values, they are the real
 * output dimensions of the files in public/img/clients and they exist so
 * next/image can reserve space without a layout shift.
 *
 * Every entry also has a .webp sibling at identical dimensions, so
 * swapping '.png' for '.webp' on any logo path resolves to a real file.
 *
 * Display names were checked one by one against both the source filename
 * and the artwork itself.
 *
 * OPEN ITEM: the Egg Farmers artwork actually reads "get cracking. Egg
 * Farmers of Ontario", so the full legal name is Egg Farmers of Ontario,
 * not Alberta and not Canada. The short form "Egg Farmers" is used here
 * because that is what was specified, but confirm with the client whether
 * the strip should say Egg Farmers of Ontario instead.
 */

export type Client = {
  name: string;
  logo: string;
  width: number;
  height: number;
};

export const clients: Client[] = [
  { name: 'AgFirst Farm Credit', logo: '/img/clients/agfirst-farm-credit.png', width: 204, height: 192 },
  { name: 'Agromark', logo: '/img/clients/agromark.jpg', width: 200, height: 147 },
  { name: 'Almond Alliance', logo: '/img/clients/almond-alliance.png', width: 270, height: 148 },
  { name: 'California Farm Bureau', logo: '/img/clients/california-farm-bureau.png', width: 148, height: 148 },
  { name: 'Cargill', logo: '/img/clients/cargill.png', width: 262, height: 148 },
  { name: 'CLAAS', logo: '/img/clients/claas.png', width: 168, height: 148 },
  { name: 'Compeer Financial', logo: '/img/clients/compeer-financial.jpg', width: 270, height: 148 },
  { name: 'Egg Farmers', logo: '/img/clients/egg-farmers.jpg', width: 800, height: 800 },
  { name: 'Farm Credit Services of America', logo: '/img/clients/farm-credit-services-of-america.png', width: 164, height: 148 },
  { name: 'Hudson Insurance', logo: '/img/clients/hudson-insurance.png', width: 270, height: 148 },
  { name: 'Indiana Farm Bureau', logo: '/img/clients/indiana-farm-bureau.jpg', width: 156, height: 148 },
  { name: 'Iowa Farm Bureau', logo: '/img/clients/iowa-farm-bureau.jpg', width: 225, height: 144 },
  { name: 'Land O\'Lakes Purina', logo: '/img/clients/land-olakes-purina.png', width: 257, height: 148 },
  { name: 'Merck', logo: '/img/clients/merck.png', width: 800, height: 361 },
  { name: 'North Dakota Grain Dealers Association', logo: '/img/clients/north-dakota-grain-dealers-association.jpg', width: 204, height: 191 },
  { name: 'Pioneer Seeds', logo: '/img/clients/pioneer-seeds.png', width: 169, height: 148 },
  { name: 'Prairie Oat Growers Association', logo: '/img/clients/prairie-oat-growers-association.jpg', width: 204, height: 192 },
  { name: 'South Dakota Soybean Association', logo: '/img/clients/south-dakota-soybean-association.png', width: 204, height: 192 },
  { name: 'Superior Livestock Auction', logo: '/img/clients/superior-livestock-auction.png', width: 218, height: 148 },
  { name: 'USAEDC', logo: '/img/clients/usaedc.png', width: 423, height: 119 },
  { name: 'Wilbur-Ellis', logo: '/img/clients/wilbur-ellis.jpg', width: 270, height: 148 },
];
