import { clients } from './clients';

/**
 * The 25 client marks, sorted by what kind of business booked him.
 *
 * WHY THIS IS A SEPARATE FILE. `content/clients.ts` is GENERATED by
 * scripts/normalize-assets.mjs from the supplied "Client Logos" folder, and it
 * is rewritten in full on every asset run. A `sector` field added there would
 * survive exactly until the next time somebody drops a logo in that folder. So
 * the taxonomy lives here, keyed by the client's display name, and the two
 * files are tied together by the guards at the foot of this one.
 *
 * WHAT THE GRAPHIC IS FOR. The logo wall answers WHO. It cannot answer what
 * kind or how many, and "how many of each kind" is the question a meeting
 * planner is actually asking when they scan a client list: is this a speaker my
 * association books, or a speaker the input suppliers book. Nine of the 25 are
 * member organizations that run an annual meeting. That is the finding, and it
 * is not visible anywhere on the site today.
 *
 * ----------------------------------------------------------------------------
 * THE TAXONOMY, AND THE TWO CALLS IT TURNS ON
 *
 * The obvious six-bucket split of an ag client list (associations, lenders,
 * inputs, processors, equipment, other) does not partition these 25 cleanly,
 * and two marks are why.
 *
 * CLAAS makes combines, forage harvesters, balers and tractors. It is not an
 * input manufacturer and it is not a processor, and dropping it into an
 * "inputs" bucket to avoid a bucket of one would put a combine maker under a
 * label that says seed and chemistry. This client sells into that industry and
 * would spot it first. So Equipment is its own bucket.
 *
 * It held ONE mark when that was written, and the note read "a bucket of one is
 * honest; a mislabelled bar is not". That argument was the right one and it is
 * kept here because it is the reason the bucket exists at all. John Deere
 * joining the wall makes it two, which settles the question rather than
 * changing the answer.
 *
 * AGROMARK is classifiable, and the artwork is what classifies it. The supplied
 * mark carries its own tagline: "Fresh produce from Spain". It is a grower and
 * exporter of fresh produce, which puts it with the businesses that buy, sell
 * and move the commodity itself rather than with the ones that sell inputs to
 * a farmer. The call is recorded on the entry.
 *
 * Everything else is read off the mark, the company's stated business line, or
 * both, and every one of the 25 carries its reasoning on its entry below.
 * ---------------------------------------------------------------------------- */

export type Sector =
  | 'associations'
  | 'lending'
  | 'inputs'
  | 'farmBureaus'
  | 'trade'
  | 'equipment';

/**
 * The printed label. Serial comma per VOICE.md section 3, plain trade words per
 * trait 5: an ag reader knows what an input supplier is and does not want it
 * glossed.
 */
export const sectorLabels: Record<Sector, string> = {
  associations: 'Commodity and trade groups',
  lending: 'Ag lending and insurance',
  inputs: 'Inputs and animal health',
  farmBureaus: 'Farm Bureaus',
  trade: 'Grain, livestock, and produce',
  equipment: 'Equipment',
};

/**
 * Declaration order, which is also the tiebreak when two sectors hold the same
 * count. The ledger sorts by count descending, so this only decides who goes
 * first among equals and it will not go stale if the roster changes.
 */
const SECTOR_ORDER: readonly Sector[] = [
  'associations',
  'lending',
  'inputs',
  'farmBureaus',
  'trade',
  'equipment',
];

/**
 * The 25 names, as literal types.
 *
 * This list is the compile-time half of the check. `clients` is typed
 * `Client[]`, so its `name` is `string` and TypeScript cannot see the 25 values
 * inside it: there is no way to make `Record<(typeof clients)[number]['name'],
 * Sector>` mean anything until the generator emits `as const`, and making it do
 * that would ripple through LogoWall, SponsorWall and every readonly boundary
 * in components/sections. So the literals are restated here, `clientSectors` is
 * exhaustive over THEM, and the runtime guard at the foot of this file proves
 * this list and the generated one are the same 25 strings.
 *
 * Net effect: adding a name here without a sector is a type error, and adding a
 * client to the generated file without adding it here fails the build.
 */
const CLIENT_NAMES = [
  'AgFirst Farm Credit',
  'Agromark',
  'Almond Alliance',
  'BASF',
  'California Farm Bureau',
  'Cargill',
  'CLAAS',
  'Compeer Financial',
  'Egg Farmers',
  'Farm Credit Services of America',
  'Helena Agri-Enterprises',
  'Hudson Insurance',
  'Indiana Farm Bureau',
  'Iowa Farm Bureau',
  'Iowa Pork Producers Association',
  'John Deere',
  "Land O'Lakes Purina",
  'Merck',
  'North Dakota Grain Dealers Association',
  'Pioneer Seeds',
  'Prairie Oat Growers Association',
  'South Dakota Soybean Association',
  'Superior Livestock Auction',
  'USAEDC',
  'Wilbur-Ellis',
] as const;

export type ClientName = (typeof CLIENT_NAMES)[number];

/**
 * One sector per client, and the reasoning on every line. A reader who
 * disagrees with a call should be able to see what it was made on without
 * leaving this file.
 */
export const clientSectors: Record<ClientName, Sector> = {
  /* Farm Credit System bank. Lends to farmers through local associations. */
  'AgFirst Farm Credit': 'lending',
  /* The supplied mark reads "Agromark: Fresh produce from Spain". A grower and
     exporter, so it sits with the businesses that move the crop rather than
     with the ones that sell a farmer his inputs. */
  Agromark: 'trade',
  /* Trade association for the California almond industry. */
  'Almond Alliance': 'associations',
  /* Crop protection and seed. An input supplier by any reading. */
  BASF: 'inputs',
  /* State Farm Bureau. */
  'California Farm Bureau': 'farmBureaus',
  /* Grain trading, oilseed crushing, and food and feed processing. It buys the
     crop, it does not sell inputs. */
  Cargill: 'trade',
  /* Combines, forage harvesters, balers, tractors. The one equipment maker on
     the wall when this bucket was created, and the reason it exists. See the
     header. */
  CLAAS: 'equipment',
  /* Farm Credit lender across Illinois, Minnesota and Wisconsin. */
  'Compeer Financial': 'lending',
  /* A producer marketing board. The artwork reads "get cracking. Egg Farmers of
     Ontario"; content/clients.ts carries the short form and flags the full name
     as an open item. Either way it is a producer organization. */
  'Egg Farmers': 'associations',
  /* Farm Credit lender for Iowa, Nebraska, South Dakota and Wyoming. */
  'Farm Credit Services of America': 'lending',
  /* Hudson Insurance Group, a crop insurance writer. Insurance sits with
     lending because both are the money side of the same farm balance sheet,
     and because one bucket of four reads better than two of two. */
  /* Crop protection distributor and applicator. Same call as Wilbur-Ellis:
     it sells the farmer his inputs, so it sits with the makers rather than in
     a distribution bucket of one. */
  'Helena Agri-Enterprises': 'inputs',
  'Hudson Insurance': 'lending',
  /* State Farm Bureau. */
  'Indiana Farm Bureau': 'farmBureaus',
  /* State Farm Bureau. */
  'Iowa Farm Bureau': 'farmBureaus',
  /* A producer organization, the same bucket the Almond Alliance and the two
     grower associations sit in. NAME UNCONFIRMED: see the note in
     scripts/normalize-assets.mjs and OPEN-ITEMS item 2. */
  'Iowa Pork Producers Association': 'associations',
  /* Tractors, combines, sprayers. The second equipment maker on the wall, which
     is what finally makes Equipment a bucket rather than a bucket of one. See
     the note in the header, which was written when CLAAS stood alone. */
  'John Deere': 'equipment',
  /* Purina animal nutrition, the feed business of the Land O'Lakes
     cooperative. Feed is an input. */
  "Land O'Lakes Purina": 'inputs',
  /* The supplied mark is the corporate Merck mark rather than Merck Animal
     Health, but animal health is the division with a reason to book an
     agriculture speaker, and it is a product sold to a producer. */
  Merck: 'inputs',
  /* Trade association of grain elevators and dealers. A member organization,
     not a trading company. */
  'North Dakota Grain Dealers Association': 'associations',
  /* Seed genetics. */
  'Pioneer Seeds': 'inputs',
  /* Grower association, Canadian prairie oat producers. */
  'Prairie Oat Growers Association': 'associations',
  /* State commodity association. */
  'South Dakota Soybean Association': 'associations',
  /* Livestock marketing. It sells cattle for producers, so it is on the same
     side of the transaction as a grain buyer. */
  'Superior Livestock Auction': 'trade',
  /* U.S. Agricultural Export Development Council. A membership council whose
     members are trade associations, cooperatives and state departments of
     agriculture, so it belongs with the member organizations rather than in a
     bucket of its own. */
  USAEDC: 'associations',
  /* Distributor of crop protection, plant nutrition and feed ingredients. */
  'Wilbur-Ellis': 'inputs',
};

export type SectorTally = {
  sector: Sector;
  label: string;
  count: number;
};

/**
 * The ledger's rows: sector, label, count, sorted by count descending. Array
 * sort is stable, so SECTOR_ORDER decides ties.
 *
 * An empty sector is dropped rather than printed as a zero. None is empty
 * today, and if the roster ever moves the last client out of one, a label with
 * nothing behind it is a category the taxonomy invented rather than a finding.
 */
export const sectorTally: SectorTally[] = SECTOR_ORDER.map((sector) => ({
  sector,
  label: sectorLabels[sector],
  count: Object.values(clientSectors).filter((value) => value === sector).length,
}))
  .filter((row) => row.count > 0)
  .sort((a, b) => b.count - a.count);

/** 25, and the ledger prints it as the total. */
export const clientTotal: number = sectorTally.reduce((sum, row) => sum + row.count, 0);

/* ============================================================================
   BUILD GUARDS

   The graphic prints a count next to a sector label. A count that does not
   match the wall two sections above it is a visible error on a page whose whole
   argument is that the numbers are checkable, so all three of these fail the
   build rather than rendering a wrong figure.
   ============================================================================ */

/* 1. This file's literal list is the same set of names as the generated one.
      This is what catches a logo drop: a new client appears in clients.ts, it
      is not in CLIENT_NAMES, and the build stops with the name in the message. */
{
  /* Apostrophes are normalized on both sides before the sets are compared, and
     that is not laziness. "Land O'Lakes Purina" is the one name on the wall
     that carries one, its form has already flipped between U+2019 and U+0027
     once in this repository when scripts/normalize-assets.mjs regenerated
     content/clients.ts, and a build that fails on an invisible character
     difference is a build nobody can debug. What this guard is for is a client
     appearing or disappearing, and it still catches that exactly. */
  const key = (name: string) => name.replace(/’/g, "'");
  const generated = clients.map((client) => key(client.name)).sort();
  const declared = [...CLIENT_NAMES].map(key).sort();
  const missing = generated.filter((name) => !declared.includes(name));
  const extra = declared.filter((name) => !generated.includes(name));
  if (missing.length > 0 || extra.length > 0) {
    throw new Error(
      `content/client-sectors.ts is out of step with the generated content/clients.ts.${
        missing.length > 0 ? ` Needs a sector: ${missing.join(', ')}.` : ''
      }${extra.length > 0 ? ` No longer a client: ${extra.join(', ')}.` : ''}`,
    );
  }
}

/* 2. The buckets sum to the roster. */
if (clientTotal !== clients.length) {
  throw new Error(
    `content/client-sectors.ts: the sectors sum to ${clientTotal} but the roster holds ${clients.length} clients.`,
  );
}

/* 3. The roster is 25, which is the figure the wall's meta line, the section
      copy and DESIGN_SYSTEM section 7.2's column counts all depend on. If this
      ever changes it is a content decision with a layout consequence, not
      something that should pass quietly. */
if (clientTotal !== 25) {
  throw new Error(
    `content/client-sectors.ts: the roster is ${clientTotal}, not 25. The logo wall's column counts and the copy on /speaking/ both assume 25.`,
  );
}
