/**
 * Client logos for the credibility strip.
 *
 * Generated by scripts/normalize-assets.mjs from the supplied "Client Logos"
 * folder. Do not hand edit the width and height values, they are the real
 * output dimensions of the files in public/img/clients and they exist so
 * next/image can reserve space without a layout shift.
 *
 * Every entry also has a .webp sibling at identical dimensions, so
 * swapping '.png' for '.webp' on any logo path resolves to a real file.
 *
 * Display names were checked one by one against both the source filename
 * and the artwork itself.
 *
 * OPEN ITEM: the Egg Farmers artwork actually reads "get cracking. Egg
 * Farmers of Ontario", so the full legal name is Egg Farmers of Ontario,
 * not Alberta and not Canada. The short form "Egg Farmers" is used here
 * because that is what was specified, but confirm with the client whether
 * the strip should say Egg Farmers of Ontario instead.
 */

export type Client = {
  name: string;
  logo: string;
  width: number;
  height: number;
};

export const clients: Client[] = [
  { name: 'AgFirst Farm Credit', logo: '/img/clients/agfirst-farm-credit.png', width: 362, height: 114 },
  { name: 'Agromark', logo: '/img/clients/agromark.jpg', width: 314, height: 90 },
  { name: 'Almond Alliance', logo: '/img/clients/almond-alliance.png', width: 466, height: 173 },
  { name: 'California Farm Bureau', logo: '/img/clients/california-farm-bureau.png', width: 234, height: 234 },
  { name: 'Cargill', logo: '/img/clients/cargill.png', width: 428, height: 190 },
  { name: 'CLAAS', logo: '/img/clients/claas.png', width: 322, height: 58 },
  { name: 'Compeer Financial', logo: '/img/clients/compeer-financial.jpg', width: 466, height: 96 },
  { name: 'Egg Farmers', logo: '/img/clients/egg-farmers.jpg', width: 228, height: 234 },
  { name: 'Farm Credit Services of America', logo: '/img/clients/farm-credit-services-of-america.png', width: 316, height: 210 },
  { name: 'Hudson Insurance', logo: '/img/clients/hudson-insurance.png', width: 466, height: 160 },
  { name: 'Indiana Farm Bureau', logo: '/img/clients/indiana-farm-bureau.jpg', width: 310, height: 152 },
  { name: 'Iowa Farm Bureau', logo: '/img/clients/iowa-farm-bureau.jpg', width: 414, height: 198 },
  /* U+2019, matching the six other places the site sets this brand name and the
     way the company sets it itself. This was the last U+0027 the site emitted:
     `name` becomes the logo's alt text and therefore the accessible name of the
     link around it. */
  { name: 'Land O’Lakes Purina', logo: '/img/clients/land-olakes-purina.png', width: 434, height: 96 },
  { name: 'Merck', logo: '/img/clients/merck.png', width: 466, height: 136 },
  { name: 'North Dakota Grain Dealers Association', logo: '/img/clients/north-dakota-grain-dealers-association.jpg', width: 292, height: 234 },
  { name: 'Pioneer Seeds', logo: '/img/clients/pioneer-seeds.png', width: 285, height: 234 },
  { name: 'Prairie Oat Growers Association', logo: '/img/clients/prairie-oat-growers-association.jpg', width: 376, height: 108 },
  { name: 'South Dakota Soybean Association', logo: '/img/clients/south-dakota-soybean-association.png', width: 284, height: 100 },
  { name: 'Superior Livestock Auction', logo: '/img/clients/superior-livestock-auction.png', width: 349, height: 234 },
  { name: 'USAEDC', logo: '/img/clients/usaedc.png', width: 466, height: 103 },
  { name: 'Wilbur-Ellis', logo: '/img/clients/wilbur-ellis.jpg', width: 394, height: 106 },
];
