/**
 * Podcast sponsors for The Business of Agriculture.
 *
 * Generated by scripts/normalize-assets.mjs from the supplied
 * "Website - List of Podcast Sponsors - Logos" folder. Width and height are
 * the real output dimensions of the files in public/img/sponsors.
 *
 * Four URLs were supplied by the client: Heads Up Plant Protectants, Tidal
 * Grow, Nano-Yield, and Good Agriculture. The other six were each looked up
 * and matched to a live official site rather than inferred from the brand
 * name, so none of them is a guess:
 *   AgView Solutions, farm transition planning, Rowley Iowa.
 *   EarthOptics, soil data mapping, Minneapolis.
 *   Harvest Returns, agriculture investment platform, Fort Worth. The www
 *     host is the live one: the apex has no A record at all.
 *   Life Scientific, crop protection, Dublin.
 *   NewFields Ag, liquid biologicals and seed treatments, Grand Mound Iowa.
 *   Redox Bio, plant bio-nutrition, Burley Idaho, trading as redoxgrows.com.
 *
 * Nano-Yield is the one logo whose SOURCE is already .webp. Its raster is
 * emitted as .png anyway, via an `ext` override in the manifest, so that it
 * gets a real .webp sibling and behaves like the other thirty marks. Left
 * alone, the .webp would be the <img src>, webpSibling() returns null for a
 * .webp source, and the .png beside it would be unreachable by construction.
 */

export type Sponsor = {
  name: string;
  logo: string;
  url: string;
  width: number;
  height: number;
};

export const sponsors: Sponsor[] = [
  { name: 'AgView Solutions', logo: '/img/sponsors/agview-solutions.jpg', url: 'https://agviewsolutions.com', width: 247, height: 234 },
  { name: 'EarthOptics', logo: '/img/sponsors/earthoptics.png', url: 'https://earthoptics.com', width: 466, height: 119 },
  { name: 'Good Agriculture', logo: '/img/sponsors/good-agriculture.png', url: 'https://goodagriculture.com', width: 466, height: 113 },
  { name: 'Harvest Returns', logo: '/img/sponsors/harvest-returns.jpg', url: 'https://www.harvestreturns.com', width: 362, height: 120 },
  { name: 'Heads Up Plant Protectants', logo: '/img/sponsors/heads-up-plant-protectants.jpg', url: 'https://headsupst.com', width: 466, height: 160 },
  { name: 'Life Scientific', logo: '/img/sponsors/life-scientific.jpg', url: 'https://lifescientific.com', width: 386, height: 68 },
  { name: 'Nano-Yield', logo: '/img/sponsors/nano-yield.png', url: 'https://nano-yield.com', width: 445, height: 234 },
  { name: 'NewFields Ag', logo: '/img/sponsors/newfields-ag.jpg', url: 'https://newfieldsag.com', width: 201, height: 234 },
  { name: 'Redox Bio', logo: '/img/sponsors/redox-bio.png', url: 'https://redoxgrows.com', width: 466, height: 178 },
  { name: 'Tidal Grow', logo: '/img/sponsors/tidal-grow.jpg', url: 'https://tidalgrowag.com', width: 402, height: 202 },
];
