/**
 * Podcast sponsors for The Business of Agriculture.
 *
 * Generated by scripts/normalize-assets.mjs from the supplied
 * "Website - List of Podcast Sponsors - Logos" folder. Width and height are
 * the real output dimensions of the files in public/img/sponsors.
 *
 * Four URLs were supplied by the client: Heads Up Plant Protectants, Tidal
 * Grow, Nano-Yield, and Good Agriculture. The other six were each looked up
 * and matched to a live official site rather than inferred from the brand
 * name, so none of them is a guess:
 *   AgView Solutions, farm transition planning, Rowley Iowa.
 *   EarthOptics, soil data mapping, Minneapolis.
 *   Harvest Returns, agriculture investment platform, Fort Worth.
 *   Life Scientific, crop protection, Dublin.
 *   NewFields Ag, liquid biologicals and seed treatments, Grand Mound Iowa.
 *   Redox Bio, plant bio-nutrition, Burley Idaho, trading as redoxgrows.com.
 *
 * Nano-Yield is the one logo whose source was already .webp, so its raster
 * is .webp and a .png fallback sits beside it.
 */

export type Sponsor = {
  name: string;
  logo: string;
  url: string;
  width: number;
  height: number;
};

export const sponsors: Sponsor[] = [
  { name: 'AgView Solutions', logo: '/img/sponsors/agview-solutions.jpg', url: 'https://agviewsolutions.com', width: 200, height: 200 },
  { name: 'EarthOptics', logo: '/img/sponsors/earthoptics.png', url: 'https://earthoptics.com', width: 800, height: 205 },
  { name: 'Good Agriculture', logo: '/img/sponsors/good-agriculture.png', url: 'https://goodagriculture.com', width: 690, height: 385 },
  { name: 'Harvest Returns', logo: '/img/sponsors/harvest-returns.jpg', url: 'https://harvestreturns.com', width: 200, height: 188 },
  { name: 'Heads Up Plant Protectants', logo: '/img/sponsors/heads-up-plant-protectants.jpg', url: 'https://headsupst.com', width: 800, height: 800 },
  { name: 'Life Scientific', logo: '/img/sponsors/life-scientific.jpg', url: 'https://lifescientific.com', width: 200, height: 148 },
  { name: 'Nano-Yield', logo: '/img/sponsors/nano-yield.webp', url: 'https://nano-yield.com', width: 640, height: 342 },
  { name: 'NewFields Ag', logo: '/img/sponsors/newfields-ag.jpg', url: 'https://newfieldsag.com', width: 132, height: 132 },
  { name: 'Redox Bio', logo: '/img/sponsors/redox-bio.png', url: 'https://redoxgrows.com', width: 270, height: 148 },
  { name: 'Tidal Grow', logo: '/img/sponsors/tidal-grow.jpg', url: 'https://tidalgrowag.com', width: 200, height: 188 },
];
